// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioScheduler.Infra.Data.Context;

#nullable disable

namespace PortfolioScheduler.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.AssetPrices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("TradingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("IX_AssetPrices_Ticker");

                    b.ToTable("AssetPrices", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.BrokerageAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .HasDatabaseName("IX_BrokerageAccounts_AccountNumber");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_BrokerageAccounts_CustomerId");

                    b.ToTable("BrokerageAccounts", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Custody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BrokerageAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageAccountId")
                        .HasDatabaseName("IX_Custodies_BrokerageAccountId");

                    b.ToTable("Custodies");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Active");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Email");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodyCustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustodyCustomerId")
                        .HasDatabaseName("IX_Deliveries_CustodyCustomerId");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("IX_Deliveries_PurchaseOrderId");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PortfolioItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("RecommendedPortfolioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedPortfolioId");

                    b.ToTable("PortfolioItems", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PortfolioRebalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BoughtTicker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RebalanceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RebalanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoldTicker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_PortfolioRebalances_CustomerId");

                    b.ToTable("PortfolioRebalances", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MasterAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionDate")
                        .HasDatabaseName("IX_PurchaseOrder_ExecutionDate");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("IX_PurchaseOrder_Ticker");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.RecommendedPortfolio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecommendedPortfolios", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.TaxEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_TaxEvents_CustomerId");

                    b.HasIndex("IsSent")
                        .HasDatabaseName("IX_TaxEvents_NotSent")
                        .HasFilter("[IsSent] = 0");

                    b.ToTable("TaxEvents", (string)null);
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.BrokerageAccount", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("PortfolioScheduler.Domain.Models.BrokerageAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Custody", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.BrokerageAccount", "BrokerageAccount")
                        .WithMany("Custodies")
                        .HasForeignKey("BrokerageAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrokerageAccount");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Delivery", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.Custody", "Custody")
                        .WithMany("Deliveries")
                        .HasForeignKey("CustodyCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioScheduler.Domain.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Deliveries")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Custody");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PortfolioItem", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.RecommendedPortfolio", "RecommendedPortfolio")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("RecommendedPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecommendedPortfolio");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PortfolioRebalance", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.Customer", "Customer")
                        .WithMany("PortfolioRebalances")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.TaxEvent", b =>
                {
                    b.HasOne("PortfolioScheduler.Domain.Models.Customer", "Customer")
                        .WithMany("TaxEvents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.BrokerageAccount", b =>
                {
                    b.Navigation("Custodies");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Custody", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.Customer", b =>
                {
                    b.Navigation("PortfolioRebalances");

                    b.Navigation("TaxEvents");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("PortfolioScheduler.Domain.Models.RecommendedPortfolio", b =>
                {
                    b.Navigation("PortfolioItems");
                });
#pragma warning restore 612, 618
        }
    }
}
